### ISSUE TITLE
redirected to http "/dashboard" (non "https")

### ISSUE THREAD

**Issue by higuchi-toshio-intec** [conwetlab/ckanext-oauth2#58]
Very thanks for your project.

My execution environment is built with these versions.
- AWS Fargate
  - CKAN [2.9.5]
  - ckanext-oauth2 [0.7.0]
- Amazon ELB (for "https" front-end listener)
- Amazon Cognito

I got a probrem with following steps.
1. browse 'https://myckan.example.com/' , and "CKAN" is displayed
1. click "Log in"
1. wait a few minutes
1. redirected "http://myckan.example.com/dashboard" and got error
   - Why "http"?
   - Why "/dashboard"?

And I got same result with this URL.
- 'https://myckan.example.com/user/logged_out_redirect'

NOTE [Success] authenticate with cognito
- 'https://myckan.example.com/dataset/'
- 'https://myckan.example.com/organization/'
- 'https://myckan.example.com/group/'

I read source files and found.
Why exists these steps? (about 79 line at "ckanext/oauth2/plugin.py")
```
    pages = ['/', '/user/logged_out_redirect']
    if came_from_url_parsed.path in pages:
        came_from_url = default_page
```

In other way
Can't I set the "default_page" specified in an environment variable?

regards

**Comment by aitormagan** [comment]
Probably you are being redirected to the HTTP site because the value of site.url in your config is not set appropriately.

Regarding de /dashboard path, is the standard CKAN behaviour.

Regards 
Aitor Magán
